### ISSUE TITLE
[onBoarding]: 2115 - Dora

### ISSUE THREAD

**Issue by deesingh08** [parallel-finance/auction-toolkit#148]
## Vault information

In order to onboarding your project on our platform, you need to provide the correct crowdloan information as following:

- [ ] ParaId: <2115>
- [ ] Lease period: <21-28>
- [ ] Cap: <15000>
- [ ] EndBlock <12,700,800>

## Project information

In order to show the correct information (name, logo, rewards rules etc), you need to create a Pull Request for this repo to add or change the details. Please following [this document](https://docs.parallel.fi/heiko-mainnet/crowdloan-v2-kusama-project-onboarding).

**Comment by deesingh08** [comment]
https://github.com/parallel-finance/auction-toolkit/pull/147

**Comment by crystalynliu** [comment]
The lease period is not correct, you need to check on polkadot.js. Also, the endblock can be found there as well.

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/parachains/crowdloan
![WX20220424-095021](https://user-images.githubusercontent.com/15072954/164952322-27315499-6778-4cd7-be9e-704a763cc691.png)

**Comment by deesingh08** [comment]
@crystalynliu : Updated the End-Cap and lease period

**Comment by crystalynliu** [comment]
I think Dora has won the auction, should we close this ticket? @deesingh08 @Helen8

**Comment by ytc92230** [comment]
I am closing the ticket s it is no longer relevant

**Comment by ytc92230** [comment]
I will close this ticket as it is no longer relevant
