### ISSUE TITLE
[onBoarding]: Listen

### ISSUE THREAD

**Issue by deesingh08** [parallel-finance/auction-toolkit#149]
## Vault information

In order to onboarding your project on our platform, you need to provide the correct crowdloan information as following:

- [ ] ParaId: <2118>
- [ ] Lease period: <21-28>
- [ ] Cap: <10000>
- [ ] EndBlock <12,700,800>

## Project information

In order to show the correct information (name, logo, rewards rules etc), you need to create a Pull Request for this repo to add or change the details. Please following [this document](https://docs.parallel.fi/heiko-mainnet/crowdloan-v2-kusama-project-onboarding).

**Comment by deesingh08** [comment]
https://github.com/parallel-finance/auction-toolkit/pull/147

**Comment by deesingh08** [comment]
@crystalynliu : Updates the lease period and end cap

**Comment by ytc92230** [comment]
@crystalynliu no update yet as BD team is trying to get in touch with project team

**Comment by ytc92230** [comment]
Project team "Listen" doesn't want the extra help at this time so we can close this issue for now
