### ISSUE TITLE
[onBoarding]: Tanganika Network

### ISSUE THREAD

**Issue by deesingh08** [parallel-finance/auction-toolkit#150]
## Vault information

In order to onboarding your project on our platform, you need to provide the correct crowdloan information as following:

- [ ] ParaId: <2116>
- [ ] Lease period: <21-28>
- [ ] Cap: <15000>
- [ ] EndBlock <12,700,800>

## Project information

In order to show the correct information (name, logo, rewards rules etc), you need to create a Pull Request for this repo to add or change the details. Please following [this document](https://docs.parallel.fi/heiko-mainnet/crowdloan-v2-kusama-project-onboarding).

**Comment by deesingh08** [comment]
https://github.com/parallel-finance/auction-toolkit/pull/147

**Comment by ytc92230** [comment]
@crystalynliu this project team has confirmed that they can distribute their own reward, so we are good to proceed further on the listing

**Comment by crystalynliu** [comment]
Already created vault
