### ISSUE TITLE
[onBoarding]: Kabocha

### ISSUE THREAD

**Issue by deesingh08** [parallel-finance/auction-toolkit#151]
## Vault information

In order to onboarding your project on our platform, you need to provide the correct crowdloan information as following:

- [ ] ParaId: <2113>
- [ ] Lease period: <22-29>
- [ ] Cap: <25000>
- [ ] EndBlock <13,161,450>

## Project information

In order to show the correct information (name, logo, rewards rules etc), you need to create a Pull Request for this repo to add or change the details. Please following [this document](https://docs.parallel.fi/heiko-mainnet/crowdloan-v2-kusama-project-onboarding).

**Comment by deesingh08** [comment]
@crystalynliu : Updated the lease period and end cap.

**Comment by ytc92230** [comment]
@crystalynliu this project team has confirmed that they can distribute their own reward, so we are good to proceed further on the listing

**Comment by ytc92230** [comment]
Hey @deesingh08 just realized the end block is wrong in this PR, it should be "
13161**540**" instead of 13,161,450 (https://kusama.subscan.io/parachain/2113)
please update, thanks!

**Comment by crystalynliu** [comment]
Already created vault.
