### ISSUE TITLE
[onBoarding]: Bajun Network

### ISSUE THREAD

**Issue by andyjsbell** [parallel-finance/auction-toolkit#163]
## Vault information

In order to onboarding your project on our platform, you need to provide the correct crowdloan information as following:

- [ ] ParaId: 2119 
- [ ] Lease period: 22-29
- [ ] Cap: 35,000
- [ ] EndBlock: 13,305,600 

## Project information

In order to show the correct information (name, logo, rewards rules etc), you need to create a Pull Request for this repo to add or change the details. Please following [this document](https://docs.parallel.fi/heiko-mainnet/crowdloan-v2-kusama-project-onboarding).

**Comment by ytc92230** [comment]
@crystalynliu project team confirmed they will be in charge of distributing reward if won; I think we are good to go

**Comment by crystalynliu** [comment]
The project has been online.
