### ISSUE TITLE
[onBoarding]: Listen 2118

### ISSUE THREAD

**Issue by deesingh08** [parallel-finance/auction-toolkit#173]
## Vault information

In order to onboarding your project on our platform, you need to provide the correct crowdloan information as following:

- [ ] ParaId: <2118>
- [ ] Lease period: <22-29>
- [ ] Cap: < 500000>
- [ ] EndBlock <13,305,600>

## Project information

In order to show the correct information (name, logo, rewards rules etc), you need to create a Pull Request for this repo to add or change the details. Please following [this document](https://docs.parallel.fi/heiko-mainnet/crowdloan-v2-kusama-project-onboarding).

**Comment by deesingh08** [comment]
@crystalynliu : The logo, rewards rules, overview are already added to the json file before. Let me know if something else needs to be done.

**Comment by ytc92230** [comment]
info reviewed, LGTM

**Comment by crystalynliu** [comment]
@ytc92230 seems this project already win the auction, but no any contributions

**Comment by ytc92230** [comment]
@crystalynliu yes we can close this issue now

**Comment by ytc92230** [comment]
@crystalynliu yes we can close this issue now
