### ISSUE TITLE
[onBoarding]: Ajuna Network

### ISSUE THREAD

**Issue by darkfriend77** [parallel-finance/auction-toolkit#196]
## Vault information

In order to onboarding your project on our platform, you need to provide the correct crowdloan information as following:

- [X] ParaId: 2057
- [X] Lease period: 10-17
- [X] Cap: 200,000.0000 DOT
- [X] EndBlock 13,374,400

## Project information

In order to show the correct information (name, logo, rewards rules etc), you need to create a Pull Request for this repo to add or change the details. Please following [this document](https://docs.parallel.fi/heiko-mainnet/crowdloan-v2-kusama-project-onboarding).

**Comment by crystalynliu** [comment]
Hi @darkfriend77 , I think the paraId is not correct. please change it. 
<img width="358" alt="image" src="https://user-images.githubusercontent.com/15072954/198514210-40ce63b8-fac7-425f-a266-8d9343bdc5bb.png">
